### ISSUE TITLE
MainJumbotron

### ISSUE THREAD

**Issue by CodeYouness** [CodeYouness/proj-html-vuejs#4]
# MainJumbotron
- components con il "Jumbotron" composto dalle 5 immagini, una centrale grande e due per lato in colonna 
- il componente ha lo stesso nome dell issue

**Comment by CodeYouness** [comment]
- usa questo branch per lavorare anche nel component mainLifeStyle per la parte composta da un immagine grande a sinistra e 3 post in colonna sulla destra

**Comment by lazzaric92** [comment]
ok capo
